"""baseline schema plus indicadores e score de priorizacao

Revision ID: 2dfe10e5654c
Revises: 
Create Date: 2026-08-04 10:17:41.247027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dfe10e5654c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classe_abc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('classe', sa.String(length=1), nullable=True),
    sa.Column('total_vendas', sa.Float(), nullable=True),
    sa.Column('percentual_individual', sa.Float(), nullable=True),
    sa.Column('percentual_acumulado', sa.Float(), nullable=True),
    sa.Column('trimestre_referencia', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id', 'trimestre_referencia', name='uq_classe_abc_cliente_trimestre')
    )
    op.create_table('indicador_retencao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('frequencia_compra', sa.String(length=30), nullable=True),
    sa.Column('classificacao', sa.String(length=30), nullable=True),
    sa.Column('dias_desde_ultimo_pedido', sa.Integer(), nullable=True),
    sa.Column('gauge', sa.String(length=20), nullable=True),
    sa.Column('ira_cair', sa.Boolean(), nullable=True),
    sa.Column('previsao_queda', sa.Date(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id')
    )
    op.create_table('nota_nps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('importado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('razao_social_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social_planilha', sa.String(length=200), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('resolvido_manualmente', sa.Boolean(), nullable=True),
    sa.Column('classe_pendente', sa.String(length=1), nullable=True),
    sa.Column('total_vendas_pendente', sa.Float(), nullable=True),
    sa.Column('percentual_individual_pendente', sa.Float(), nullable=True),
    sa.Column('percentual_acumulado_pendente', sa.Float(), nullable=True),
    sa.Column('trimestre_referencia_pendente', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razao_social_planilha')
    )
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score_prioridade', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('motivo_prioridade', sa.Text(), nullable=True))
        # NOTA: o banco de produção tem as colunas legadas 'status_cobranca',
        # 'valor_pendente' (cliente) e 'observacoes' (proposta) que nunca foram
        # declaradas nos models (eram @property calculadas). O autogenerate do
        # Alembic sugeriu removê-las, mas isso é destrutivo e fora do escopo
        # desta refatoração — mantidas intactas, apenas não mapeadas no ORM.

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('motivo_prioridade')
        batch_op.drop_column('score_prioridade')

    op.drop_table('razao_social_alias')
    op.drop_table('nota_nps')
    op.drop_table('indicador_retencao')
    op.drop_table('classe_abc')
    # ### end Alembic commands ###
