"""adiciona motivo_pendencia e candidatos ambiguos em RazaoSocialAlias

Revision ID: 987a1045d3a7
Revises: 2dfe10e5654c
Create Date: 2026-08-04 10:51:20.743067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987a1045d3a7'
down_revision = '2dfe10e5654c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTA: mantidas as colunas legadas 'status_cobranca'/'valor_pendente'/
    # 'observacoes_internas' (cliente) e 'observacoes' (proposta) — ver
    # comentário equivalente na migration 2dfe10e5654c.
    with op.batch_alter_table('razao_social_alias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo_pendencia', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('candidatos_ambiguos_ids', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('razao_social_alias', schema=None) as batch_op:
        batch_op.drop_column('candidatos_ambiguos_ids')
        batch_op.drop_column('motivo_pendencia')

    # ### end Alembic commands ###
