"""adiciona data_cadastro em Cliente

Revision ID: 9c625bca3299
Revises: 987a1045d3a7
Create Date: 2026-08-04 13:22:26.024672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c625bca3299'
down_revision = '987a1045d3a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTA: mantidas as colunas legadas 'status_cobranca'/'observacoes_internas'/
    # 'valor_pendente' (cliente) e 'observacoes' (proposta) — ver comentário
    # equivalente nas migrations 2dfe10e5654c e 987a1045d3a7.
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_cadastro', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('data_cadastro')

    # ### end Alembic commands ###
