"""adiciona data_ultima_mudanca_status em Proposta

Revision ID: d0157ea7d483
Revises: 9c625bca3299
Create Date: 2026-08-13 15:37:18.994806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0157ea7d483'
down_revision = '9c625bca3299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTA: mantidas as colunas legadas 'valor_pendente'/'observacoes_internas'/
    # 'status_cobranca' (cliente) — ver comentário equivalente nas migrations
    # 2dfe10e5654c, 987a1045d3a7 e 9c625bca3299.
    with op.batch_alter_table('proposta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_ultima_mudanca_status', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###

    # Backfill: para propostas já existentes, usa data_criacao_proposta como
    # valor inicial de data_ultima_mudanca_status (é a melhor aproximação
    # disponível — não temos histórico real de quando o status mudou pela
    # última vez antes desta coluna existir).
    proposta = sa.table(
        'proposta',
        sa.column('id', sa.Integer),
        sa.column('data_criacao_proposta', sa.DateTime),
        sa.column('data_ultima_mudanca_status', sa.DateTime),
    )
    op.execute(
        proposta.update()
        .where(proposta.c.data_ultima_mudanca_status.is_(None))
        .values(data_ultima_mudanca_status=proposta.c.data_criacao_proposta)
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposta', schema=None) as batch_op:
        batch_op.drop_column('data_ultima_mudanca_status')

    # ### end Alembic commands ###
